name: Moodle Plugin CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_HOST_AUTH_METHOD: 'trust'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
      
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1']
        moodle-branch: ['MOODLE_403_STABLE']
        database: ['pgsql']
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: plugin

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pgsql, soap, zip, gd, xmlrpc, intl
          ini-values: max_input_vars=5000
          coverage: none

      - name: Deploy moodle-plugin-ci
        run: |
          composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
          echo $(cd ci/bin; pwd) >> $GITHUB_PATH

      - name: Install Moodle
        run: moodle-plugin-ci install --plugin ./plugin --db-host=127.0.0.1
        env:
          DB: ${{ matrix.database }}
          MOODLE_BRANCH: ${{ matrix.moodle-branch }}

      - name: PHP Lint
        run: moodle-plugin-ci phplint

      - name: PHP Copy/Paste Detector
        run: moodle-plugin-ci phpcpd

      - name: PHP Mess Detector
        run: moodle-plugin-ci phpmd

      - name: Moodle Code Checker
        run: moodle-plugin-ci codechecker

      - name: Moodle PHPDoc Checker
        run: moodle-plugin-ci phpdoc

      - name: Validating
        run: moodle-plugin-ci validate

      - name: Check Upgrade Savepoints
        run: moodle-plugin-ci savepoints

      - name: PHPUnit Tests
        run: moodle-plugin-ci phpunit

      - name: Behat Features
        run: moodle-plugin-ci behat --profile chrome
